version: "3.8"
services:
  postgres-server:
    image: "postgres"
    restart: always
    ports:
      - "5431:5432"
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      ENVIRONMENT: production
    depends_on:
      - postgres-server